# Generated by Django 5.2 on 2025-04-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
