# Generated by Django 5.2 on 2025-05-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_dailyexpense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
            ],
        ),
    ]
