# Generated by Django 5.2 on 2025-05-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_custom_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='custom_project',
        ),
    ]
