# Generated by Django 5.2 on 2025-05-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_custom_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_expenses', to='projects.customproject'),
        ),
    ]
