# Generated by Django 5.2 on 2025-06-10 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_remove_siteimage_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteimage',
            name='date_uploaded',
        ),
        migrations.AddField(
            model_name='siteimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_images', to='projects.project'),
        ),
    ]
