# Generated by Django 5.2 on 2025-07-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_siteimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='billing-site-img/'),
        ),
    ]
