# Generated by Django 5.2 on 2025-04-29 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_expense_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project'),
        ),
    ]
