# Generated by Django 5.2 on 2025-05-03 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_customproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='custom_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.customproject'),
        ),
    ]
