# Generated by Django 5.2 on 2025-05-09 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpense',
            name='category',
            field=models.CharField(default='food', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
