# Generated by Django 5.2 on 2025-05-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_expensedaily'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseDaily',
        ),
        migrations.AddField(
            model_name='dailyexpense',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
