# Generated by Django 5.2 on 2025-06-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_delete_expensedaily_dailyexpense_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='unit',
            field=models.CharField(default='sq ft', max_length=50, null=True),
        ),
    ]
