# Generated by Django 5.2 on 2025-06-10 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_siteimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteimage',
            name='client_name',
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='description',
            field=models.TextField(blank=True, default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
