# Generated by Django 5.2 on 2025-07-04 09:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_remove_siteimage_date_uploaded_siteimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
