# Generated by Django 5.2.11 on 2026-03-25 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_projectnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectNote',
            new_name='PaymentNote',
        ),
        migrations.RemoveField(
            model_name='paymentnote',
            name='project',
        ),
        migrations.AddField(
            model_name='paymentnote',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.payment'),
            preserve_default=False,
        ),
    ]
